version: "3"
services:
  chatbot:
    image: 7940image
    environment:
      ACCESS_TOKEN: 5778452675:AAFYX2aD0nvv489JI6v5bTpC5dbsvPsMA1U
      HOST: redis
      PASSWORD: comp7940passwordlab8
      REDISPORT: 6379
      OPENAI_API_KEY: "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"
    command: python chatbot.py
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]
